<?php

/**
 * @file
 * Contains d324_core.module.
 */

// To have all d324 core general and global tokens.
use Drupal\Core\Template\Attribute;

\Drupal::moduleHandler()->loadInclude('d324_core', 'inc', 'd324_core.tokens');

/**
 * Implements hook_FORM_ID_form_alter.
 */
function d324_core_form_node_form_alter(&$form, $form_state) {
  // Override node form sidebar order.
  if (isset($form['author'])) {
    $form['author']['#weight'] = -6;
  }
  if (isset($form['field_comments'])) {
    $form['field_comments']['widget'][0]['#weight'] = -5;
  }
  if (isset($form['path_settings'])) {
    $form['path_settings']['#weight'] = -4;
  }
  if (isset($form['field_meta_tags'])) {
    $form['field_meta_tags']['widget'][0]['#weight'] = -3;
  }
  if (isset($form['simple_sitemap'])) {
    $form['simple_sitemap']['#weight'] = -2;
  }
  if (isset($form['ds_switch_view_mode'])) {
    $form['ds_switch_view_mode']['#weight'] = 101;
  }
}

/**
 * Implements hook_template_preprocess_default_variables_alter().
 */
function d324_core_template_preprocess_default_variables_alter(&$variables) {
  $user_settings_config = \Drupal::config('user.settings');
  $variables['user_settings_register_admin_only'] = $user_settings_config->get('register') == 'admin_only' ? 1 : 0;
}

/**
 * Implements hook_theme().
 */
function d324_core_theme($existing, $type, $theme, $path) {
  return [
    'd324_header_image_block' => [
      'variables' => [
        'page_title' => '',
        'media' => NULL,
        'wrapper_attributes' => NULL,
        'overlay_attributes' => NULL,
        'title_attributes' => NULL,
      ],
    ],
  ];
}
